### ISSUE TITLE
Is Shukla stability available?

### ISSUE THREAD

**Issue by kwstat** [TheRocinante-lab/GEmetrics#1]
Is it possible to obtain Shukla stability statistics with your methods?

**Comment by SimonRio** [comment]
Hello, for the moment the Shukla stability statistic is not implemented in the package. However, this measure is closely linked to ecovalence (up to a constant and a coefficient common to all individuals). This means that genotypes would be classified identically according to their stability using both measures.

**Comment by kwstat** [comment]
Thanks
